module.exports = {
  apps: [
    {
      name: "btc-5m-arrival",
      cwd: "/Users/caoxiangrui/Desktop/external/polymarket_backtest",
      script: "./scripts/run_btc_5m_arrival.sh",
      interpreter: "bash",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 10000,
      time: true,
      merge_logs: true,
      out_file: "./logs/btc_5m_arrival.out.log",
      error_file: "./logs/btc_5m_arrival.err.log",
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "tail-reversal-095",
      cwd: "/Users/caoxiangrui/Desktop/external/polymarket_backtest",
      script: "./scripts/run_tail_reversal.sh",
      interpreter: "bash",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 10000,
      time: true,
      merge_logs: true,
      out_file: "./logs/tail_reversal_095.out.log",
      error_file: "./logs/tail_reversal_095.err.log",
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "btc-5m-arrival-complex",
      cwd: "/Users/caoxiangrui/Desktop/external/polymarket_backtest",
      script: "./scripts/run_btc_5m_arrival_complex.sh",
      interpreter: "bash",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 10000,
      time: true,
      merge_logs: true,
      out_file: "./logs/btc_5m_arrival_complex.out.log",
      error_file: "./logs/btc_5m_arrival_complex.err.log",
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "btc-15m-last5m-misalignment",
      cwd: "/Users/caoxiangrui/Desktop/external/polymarket_backtest",
      script: "./scripts/run_completeness_arb_last5m.sh",
      interpreter: "bash",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 10000,
      time: true,
      merge_logs: true,
      out_file: "./logs/btc_15m_last5m_misalignment.out.log",
      error_file: "./logs/btc_15m_last5m_misalignment.err.log",
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "btc-5m-volatility",
      cwd: "/Users/caoxiangrui/Desktop/external/polymarket_backtest",
      script: "./scripts/run_btc_5m_volatility.sh",
      interpreter: "bash",
      autorestart: false,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 10000,
      time: true,
      merge_logs: true,
      out_file: "./logs/btc_5m_volatility.out.log",
      error_file: "./logs/btc_5m_volatility.err.log",
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
  ],
};
